global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: sh-gateway
    honor_labels: true
    static_configs:
      - targets:
          - '10.88.111.3:3000'
  - job_name: grafana
    honor_labels: true
    static_configs:
      - targets:
        - '10.88.111.3:9092'